import random

def main():
    print('Welcome to my clone of Wordle! The rules are simple:')
    print('Try and guess the 5 letter word generated by the computer. You have 6 tries.')
    print('If your letter is correct and in the right spot, brackets like these [] will surround it.')
    print('If your letter is correct and in the wrong spot, these brackets {} will surround it.')
    print('If your guess is incorrect, nothing special will happen.')
    play = input('do you want to play? y/n: ')
    while play == 'y':
        wordlst = create_word_list()
        goal = random_word(wordlst)
        target=goal.lower()
        #print(target)
        
        
        count = 0
        guess = input('guess a word: ')
        lowerguess = guess.lower()
        
        while len(guess) != 5:
            print('Please enter a valid 5 letter word')
            guess = (input('guess a word: '))
            lowerguess = guess.lower()
        
        #maybe add something here about only writing valid english words
        while lowerguess!= target and count < 5:
            if lowerguess != target:
                #word is printed no matter what
                #here is where the user input is printed
                outcome= (determine_word(lowerguess, target))
                if outcome == 'your guess is out of range, please enter a 5 letter word':
                    count -= 1
                    print(outcome.upper())
                else:
                    width = 40
                    padding = ' '
                    print(f'{outcome.upper():{padding}>{width}}')
                try:
                    guess = (input('guess a word: '))
                    lowerguess = guess.lower()
                except IndexError:
                    print('Please enter a valid 5 letter word')
                    guess = (input('guess a word: '))
                    lowerguess = guess.lower()
            #if user guesses correct word they win
            count+=1
            
        if lowerguess == target:
            outcome= (determine_word(lowerguess, target)).upper()
            width = 40
            padding = ' '
            print(f'{outcome:{padding}>{width}}')
            print('congratulations you win')
        else: 
            #after the 6 tries are up the game prints that the user loses
            print('you lose')
            print(f'The word was {target.upper()}')
            
            #ask them if they want to play again
        play = input('do you want to play? y/n: ')

def create_word_list():
    words = []
    #this creates a list of five letter words by reading from a file of words
    #that i have created
    myfile = open('words.txt', 'r', encoding = "ISO-8859-1")
    line = myfile.readline()
    for line in myfile:
        words.append(line.rstrip())
        line = myfile.readline()
    return words

def random_word(a_list):
    word = random.choice(a_list)
    return word

def determine_word(guessstr, realstr):
    count = 0
    newlist = []
    altcount = 0
    #if guess is less than 5 letters the program returns this statement
    if len(guessstr) < 5:
        newstr = 'your guess is out of range, please enter a 5 letter word'
    else:
        try:
            #characters that are in the word but not in the right position are
            #put in brackets while the characters in the right spot are put
            #in regular brackets
            for char in guessstr:
                #add characters to a new list
                if char == realstr[count]:
                    rightchar = '[' + char +']'
                    newlist.append(rightchar)
                elif char in realstr and char != realstr[count]:
                    rightchar = '{'+char+'}'
                    newlist.append(rightchar)
                else:
                    newlist.append(char)
                count += 1

            #turn new list into a string
            newstr = ''.join(newlist)
        
        #if guess is more than 5 letters, the program returns this statement
        except IndexError:
            newstr = 'your guess is out of range, please enter a 5 letter word'
        
    #return the new string with the edits
    return newstr

    
main()    
    
